### ISSUE TITLE
Allow moving the app by dragging from the border of the search bar

### ISSUE THREAD

**Issue by dubisdev** [kunkunsh/kunkun#74]
**Is your feature request related to a problem? Please describe.**
The first thing I tried when I run the app for first time was moving the app window. I tried doing it from the top search bar, but I couldn't.

**Describe the solution you'd like**
I'd like to be able to move the app window from the search bar border.

**Describe alternatives you've considered**
Now it is possible to do this, but from other parts of the app (bottom bar)

**Additional context**

https://github.com/user-attachments/assets/a5850648-7ecb-4b98-bb02-06ba2f712147

**Comment by HuakunShen** [comment]
Border is for resizing the window, I set the entire bottom bar to be draggable.
I could also make the three dot menu button in the top right corner draggable.

**Comment by HuakunShen** [comment]
![image](https://github.com/user-attachments/assets/9e290768-6c90-47f0-9562-2c3a4ebf7361)

Add built-in command "Show Draggable Region" https://github.com/kunkunsh/kunkun/commit/5301e620ce205bc4332d1c439b9c92281e587552
