### ISSUE TITLE
BUG: Bun crashes when building extension

### ISSUE THREAD

**Issue by jonasrafa** [kunkunsh/kunkun#78]
**Describe the bug**
Bun crashes when building extension. The error says it's a Bun problem, but I tried reinstalling it, and I tested it in another project and Bun is working, so I imagine it must be something with Kunkun that's causing the error.

I tested with React Custom UI and had no problems.

**To Reproduce**
1. Run npm init kunkun@latest in the terminal.
2. Choose the "Preset Template (Web Worker)" option during setup.
3. Install dependencies with pnpm install.
4. Start the development server with pnpm dev

**Error**
```
Bun v1.1.31 (e448c4cc) Windows x64
Windows v.win10_fe
CPU: sse42 avx avx2
Args: "C:\Users\Jonas\.bun\bin\bun.exe" "build" "--minify" "--target=browser" "--outdir=./dist" "./src/index.ts"
Features: tsconfig(6)
Elapsed: 368ms | User: 0ms | Sys: 46ms
RSS: 119.24MB | Peak: 119.24MB | Commit: 0.19GB | Faults: 29604

panic(thread 19768): Expected pretty file path to have only forward slashes, got 'A:\Desktop\New folder\test\node_modules\.pnpm\@kksh+api@0.0.12-beta.4_typescript@5.6.3\node_modules\@huakunshen\comlink\dist\esm\comlink.mjs'
oh no: Bun has crashed. This indicates a bug in Bun, not your code.

To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:

 https://bun.report/1.1.31/wb1e448c4cAggggggCyzrrM6m8qMm4/+Bqo3gMCYKERNEL32.DLL65yECSntdll.dllwz3WA0eNpVyztuAjEQANCrTEcBsfgkKVItErScYCRk1rOx8WdGnllgb5+KIu2T3vklNBoFkE5mC0ypEIi3CMYQ/YOAW1lg4v70PYAWr5F0A79ssDr+4Ik0Gwte6AkTl0AdjdSwcaBr5TAXUnTSpOKQs8a1lzRs3dbt9h83Mu8+r7YI6diT2PDlvt3h/x3i7PPcNFLDkWtJLWNIakha3+DqXVd/e+5LAg

12 | export default "unknown";
                    ^
ShellError: Failed with exit code 3
 info: {
  "exitCode": 3,
  "stderr": "============================================================\nBun v1.1.31 (e448c4cc) Windows x64\nWindows v.win10_fe\nCPU: sse42 avx avx2\nArgs: \"C:\\Users\\Jonas\\.bun\\bin\\bun.exe\" \"build\" \"--minify\" \"--target=browser\" \"--outdir=./dist\" \"./src/index.ts\"\nFeatures: tsconfig(6) \nElapsed: 368ms | User: 0ms | Sys: 46ms\nRSS: 119.24MB | Peak: 119.24MB | Commit: 0.19GB | Faults: 29604\n\npanic(thread 19768): Expected pretty file path to have only forward slashes, got 'A:\\Desktop\\New folder\\test\\node_modules\\.pnpm\\@kksh+api@0.0.12-beta.4_typescript@5.6.3\\node_modules\\@huakunshen\\comlink\\dist\\esm\\comlink.mjs'\noh no: Bun has crashed. This indicates a bug in Bun, not your code.\n\nTo send a redacted crash report to Bun's team,\nplease file a GitHub issue using the link below:\n\n https://bun.report/1.1.31/wb1e448c4cAggggggCyzrrM6m8qMm4/+Bqo3gMCYKERNEL32.DLL65yECSntdll.dllwz3WA0eNpVyztuAjEQANCrTEcBsfgkKVItErScYCRk1rOx8WdGnllgb5+KIu2T3vklNBoFkE5mC0ypEIi3CMYQ/YOAW1lg4v70PYAWr5F0A79ssDr+4Ik0Gwte6AkTl0AdjdSwcaBr5TAXUnTSpOKQs8a1lzRs3dbt9h83Mu8+r7YI6diT2PDlvt3h/x3i7PPcNFLDkWtJLWNIakha3+DqXVd/e+5LAg\n\n",
  "stdout": ""
}

      at new ShellError (unknown:12:16)
      at new ShellPromise (unknown:72:16)
      at BunShell (unknown:187:35)
      at A:\Desktop\New folder\test\build.ts:9:3
      at build (A:\Desktop\New folder\test\build.ts:7:6)
      at module code (A:\Desktop\New folder\test\build.ts:21:2)
      at unknown:2:1
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 23H2 22631.4391
 
**KunKun version**
- Version: 0.1.9-beta.4

**Additional context**
This error also happen with "pnpm build"

**Comment by HuakunShen** [comment]
I also got this error on Windows. This app hasn't been carefully tested on Windows yet, I will fix this issue.

**Comment by HuakunShen** [comment]
This is a Bun bug, and only happens when dependencies are installed with `pnpm install`

Related issues: 

- https://github.com/oven-sh/bun/issues/14787
- https://github.com/oven-sh/bun/issues/14843

I have 2 simple solutions for windows.
1. Use WSL (Windows Subsystem for Linux)
2. Remove `node_modules`, reinstall dependencies with `bun install`  or `npm install` rather than `pnpm install`

**Comment by jonasrafa** [comment]
In the latest version (npm init kunkun@latest) I couldn't do the test, because it gives this error when creating the project
```
Outdir: A:\Desktop\test
? Select an Extension Template Preset Template (Web Worker)
? Enter Extension Name teste2
Template Source Path: A:\Desktop\test\node_modules\create-kunkun\dist\templates\template-ext-worker.tgz
node:fs:1032
  binding.rename(
          ^

Error: EXDEV: cross-device link not permitted, rename 'C:\Users\Jonas\AppData\Local\Temp\create-kunkun-extractuUBoT3\template-ext-worker' -> 'A:\Desktop\test\teste2'
    at Object.renameSync (node:fs:1032:11)
    at file:///A:/Desktop/test/node_modules/create-kunkun/dist/index.mjs:20096:29
    at async copyTemplate (file:///A:/Desktop/test/node_modules/create-kunkun/dist/index.mjs:20201:3)
    at async file:///A:/Desktop/test/node_modules/create-kunkun/dist/index.mjs:20256:15 {
  errno: -4037,
  code: 'EXDEV',
  syscall: 'rename',
  path: 'C:\\Users\\Jonas\\AppData\\Local\\Temp\\create-kunkun-extractuUBoT3\\template-ext-worker',
  dest: 'A:\\Desktop\\test\\teste2'
}

Node.js v20.18.0
npm error code 1
npm error path A:\Desktop\test
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c create-akun
npm error A complete log of this run can be found in: C:\Users\Jonas\AppData\Local\npm-cache\_logs\2024-10-28T11_35_46_008Z-debug-0.log
```

When I run this command “npm init kunkun@latest”, for some reason it never picks up the latest version of create-kunkun, but an earlier version (0.1.24), and I get this warning “You are using create-kunkun version 0.1.24, but the latest version is 0.1.25. It may not work with the latest Kunkun app.”

But in version 0.1.22 (npm init kunkun@0.1.22), the “bun install” worked, but the “npm run dev” keeps giving this error below, and ends up not automatically updating the extension within Kunkun, I have to keep going to the Kunkun home screen and opening the extension after any update.

```
Send Refresh Worker Extension Request
Failed to refresh worker extension: 41 |                switch (platform) {
42 |                    case "darwin":
43 |                            await Bun.spawn(["open", `kunkun://${DEEP_LINK_PATH_REFRESH_DEV_EXTENSION}`])
44 |                            break
45 |                    case "win32":
46 |                            await Bun.spawn(["start", `kunkun://${DEEP_LINK_PATH_REFRESH_DEV_EXTENSION}`])
                   ^
TypeError: Executable not found in $PATH: "start"
 code: "ERR_INVALID_ARG_TYPE"

      at A:\Desktop\test\test\node_modules\@kksh\api\src\dev\index.ts:46:15
```

**Comment by HuakunShen** [comment]
1. The latest version issue was a typo. The wrong latest version was embeded into the code. So you are on the latest version.
2. I noticed the error in 0.1.22, it was another Bun windows incompatibility issue, it was fixed with `child_process` `exec` 
3. I am not sure what's going on with `npm init`, I could run it on my Win11 with no problem. Yesterday a `tar` package was added to store templates, not sure if that package caused any problem, but I had no problem. Maybe it's related to your windows powershell execution policy, let me experiment with it.

![image](https://github.com/user-attachments/assets/fc3007a0-d12f-40fb-8e41-8ce03bcd5c4b)

**Comment by HuakunShen** [comment]
I see! The error is `cross-device link not permitted` and you are on `A:` drive. 
It's trying to copy from C drive to A drive, that's why it failed. 
Give me a moment, I will fix it.

**Comment by jonasrafa** [comment]
That's the problem, I tested it on the C drive and it worked now.

**Comment by HuakunShen** [comment]
Wait, the refresh issue isn't fixed in the latest version yet, it's in another branch and I forgot to merge it, please let me fix them.

**Comment by HuakunShen** [comment]
@jonasrafa All fixed and tested. 0.1.27 should work now.
